//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myoutlet.ge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class callRequest
    {
        public int Id { get; set; }
        public int PhoneNum { get; set; }
        public int ProductId { get; set; }
        public bool Status { get; set; }
        public Nullable<int> PartnerId { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
    }
}
