//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myoutlet.ge.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyoutletEntities : DbContext
    {
        public MyoutletEntities()
            : base("name=MyoutletEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Add> Adds { get; set; }
        public virtual DbSet<Barcode> Barcodes { get; set; }
        public virtual DbSet<callRequest> callRequests { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Description> Descriptions { get; set; }
        public virtual DbSet<FbLink> FbLinks { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<HotDiscount> HotDiscounts { get; set; }
        public virtual DbSet<InstaLink> InstaLinks { get; set; }
        public virtual DbSet<Kind> Kinds { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RecentyAdded> RecentyAddeds { get; set; }
        public virtual DbSet<Sub_admin> Sub_admin { get; set; }
        public virtual DbSet<ValuablePartner> ValuablePartners { get; set; }
        public virtual DbSet<WeeklyDiscount> WeeklyDiscounts { get; set; }
        public virtual DbSet<YoutubeLink> YoutubeLinks { get; set; }
    }
}
