//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myoutlet.ge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string Fullname { get; set; }
        public string Mail { get; set; }
        public string Address { get; set; }
        public string orderHashId { get; set; }
        public string orderId { get; set; }
        public Nullable<bool> status { get; set; }
        public string City { get; set; }
        public string Mobile { get; set; }
    }
}
