//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myoutlet.ge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.callRequests = new HashSet<callRequest>();
            this.Comments = new HashSet<Comment>();
            this.Descriptions = new HashSet<Description>();
            this.HotDiscounts = new HashSet<HotDiscount>();
            this.RecentyAddeds = new HashSet<RecentyAdded>();
            this.WeeklyDiscounts = new HashSet<WeeklyDiscount>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public decimal SaleInPercent { get; set; }
        public string ShoppingLink { get; set; }
        public int KindId { get; set; }
        public int CategoryId { get; set; }
        public int PartnerId { get; set; }
        public Nullable<decimal> ProductUniqueNum { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public Nullable<decimal> SaledCost { get; set; }
        public string City { get; set; }
        public Nullable<int> productCount { get; set; }
        public string saleReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<callRequest> callRequests { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Description> Descriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotDiscount> HotDiscounts { get; set; }
        public virtual Kind Kind { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecentyAdded> RecentyAddeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeeklyDiscount> WeeklyDiscounts { get; set; }
    }
}
