//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myoutlet.ge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuablePartner
    {
        public int Id { get; set; }
        public int Partner { get; set; }
    
        public virtual Partner Partner1 { get; set; }
    }
}
